### ISSUE TITLE
Is it possible to get hold of your paper? 

### ISSUE THREAD

**Issue by Paandaman** [Vottivott/building-a-swedish-qa-model#1]
First off, interesting repository and thanks for uploading the datasets! 
Secondly, I wonder if it's possible to get access to the "Building a Swedish Question-Answering Model" paper? I'm in need of a Swedish version of SQUAD for a project I'm working on and I would love to see how you translated the English dataset!

**Comment by DanielHesslow** [comment]
As it's not yet published we're not quite sure of whether or not it's allowed to be uploaded here.  Give me your email or send me an email at Daniel.hesslow@gmail.com and I'll send it to you. 

Happy to answer any questions you have about it

**Comment by DanielHesslow** [comment]
Thanks for you interest, I've uploaded a [preprint here.](Building_a_Swedish_Question_Answering_Model_Preprint.pdf)

I'm happy to answer any questions you might have about it over email.

**Comment by Paandaman** [comment]
Thanks a lot, I really appreciate it! I'll send you an e-mail if any questions arises.
